default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: event_manage_dev # Your PostgreSQL username
  password: Ad@161104 # Your PostgreSQL password
  pool: 5

development:
  <<: *default
  database: event_manage_development

test:
  <<: *default
  database: event_manage_test

production:
  <<: *default
  database: event_manage_production
  username: event_manage
  password: <%= ENV["EVENT_MANAGE_DATABASE_PASSWORD"] %>
