pin "application"
pin "@rails/ujs", to: "@rails--ujs.js"
pin "@hotwired/turbo-rails", to: "@hotwired--turbo-rails.js"
pin "@hotwired/turbo", to: "@hotwired--turbo.js"
pin "@rails/actioncable/src", to: "@rails--actioncable--src.js"
pin_all_from "app/javascript/controllers", under: "controllers"
